name: Update README.md

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Setup Python
        uses: actions/setup-python@v5.0.0

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.1.0

      - name: Update README.md
        run: |
          python feed.py

      - name: Commit README.md
        run: |
          timestamp=$(date -u)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Automated update: ${timestamp} ${GITHUB_SHA}" || echo "No changes to commit"

      - name: Push README.md
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
